USE [Core]
GO

/****** Object:  Table [contact].[PERSON]    Script Date: 27-Sep-19 9:17:55 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [contact].[PERSON](
	[BIRTHDATE] [datetime2](0) NULL,
	[CLTSINCE] [datetime2](0) NULL,
	[CREATEDATE] [datetime2](0) NULL,
	[CREATEOP] [varchar](20) NULL,
	[CUSTSTATUS] [varchar](1) NULL,
	[DNI] [varchar](20) NULL,
	[EDUCATION] [varchar](30) NULL,
	[EMAIL] [varchar](255) NULL,
	[EMPLOYMENT] [varchar](60) NULL,
	[FIRSTNAME] [nvarchar](40) NULL,
	[FIRSTNAME2] [nvarchar](40) NULL,
	[GENDER] [varchar](10) NULL,
	[LANGUAGE_] [varchar](20) NULL,
	[LASTNAME] [nvarchar](40) NULL,
	[LASTNAME2] [nvarchar](40) NULL,
	[LASTUPDDAT] [datetime2](0) NULL,
	[LASTUPDOP] [varchar](20) NULL,
	[MAIDENNAME] [nvarchar](30) NULL,
	[MAILSTOP] [varchar](1) NULL,
	[MARSTAT] [varchar](30) NULL,
	[MIDDLENAME] [nvarchar](40) NULL,
	[NATIONALTY] [varchar](40) NULL,
	[OCCUPATION] [varchar](30) NULL,
	[PERSONID] [varchar](10) NOT NULL,
	[SALUTATION] [varchar](15) NULL,
	[PINFLAG] [varchar](1) NULL,
	[VCSTATUS] [varchar](1) NULL,
	[VCSUMMARY] [varchar](2) NULL,
	[VCDATE] [datetime2](0) NULL,
	[VCID] [varchar](1) NULL,
	[VCENABLED] [varchar](1) NULL,
	[VCERRMSG] [varchar](255) NULL,
	[VCDAY] [datetime2](0) NULL,
	[VCTIME] [datetime2](0) NULL,
	[CUSTTYPE] [char](1) NULL,
	[CUSTOWNER] [char](3) NULL,
	[BROKERNO] [int] NULL,
	[CLTLOGINDATE] [datetime2](0) NULL,
	[EMAILSTOP] [varchar](1) NULL,
	[CALLSTOP] [varchar](1) NULL,
	[DECEASED] [char](1) NULL,
	[DOCUMENTSOK] [char](1) NULL,
	[RETIRED_DATE] [datetime2](0) NULL,
	[SINGLE_CIF] [varchar](10) NULL,
	[RISK_CODE] [char](3) NULL,
	[EMPLOYEE_ID] [int] NULL,
	[RETURNED_MAIL_FLAG] [char](1) NULL,
	[DRIVING_LICENCE] [varchar](24) NULL,
	[FIRST_OE_ACCOUNT_OPEN_DATE] [datetime2](0) NULL,
	[IS_EMAIL_VALID] [char](1) NULL,
	[NO_EMAIL_VERIFIED_DATE] [datetime2](0) NULL,
	[LAST_CUST_REPLIED_NO_EMAIL_DT] [datetime2](0) NULL,
	[ID_VERIFIED_INDICATOR] [varchar](3) NULL,
	[ID_VERIFIED_DATE] [datetime2](0) NULL,
	[TRIX_WATCH_ARREARS_FLAG] [char](1) NULL,
	[EMPLOYMENT_TYPE_REF_ID] [smallint] NULL,
	[SMSSTOP] [varchar](1) NULL,
	[BANNERSTOP] [varchar](1) NULL,
	[SOURCE_WEALTH_ID] [int] NULL,
	[SOURCE_WEALTH_OTHER] [varchar](100) NULL,
	[SOURCE_FUNDS_ID] [int] NULL,
	[SOURCE_FUNDS_OTHER] [varchar](100) NULL,
	[INSURANCE_ONLY] [char](1) NULL,
	[IS_VULNERABLE] [char](1) NOT NULL,
 CONSTRAINT [PERSON_PK] PRIMARY KEY CLUSTERED 
(
	[PERSONID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [USERSPACE]
) ON [USERSPACE]

GO

ALTER TABLE [contact].[PERSON] SET (LOCK_ESCALATION = AUTO)
GO

ALTER TABLE [contact].[PERSON] ADD  CONSTRAINT [DF__PERSON__DECEASED__2FDA0782]  DEFAULT ('N') FOR [DECEASED]
GO

ALTER TABLE [contact].[PERSON] ADD  CONSTRAINT [DF__PERSON__DOCUMENT__30CE2BBB]  DEFAULT ('N') FOR [DOCUMENTSOK]
GO

ALTER TABLE [contact].[PERSON] ADD  CONSTRAINT [DF__PERSON__RISK_COD__31C24FF4]  DEFAULT ('LOW') FOR [RISK_CODE]
GO

ALTER TABLE [contact].[PERSON] ADD  CONSTRAINT [SMSSTOP_DEFAULT]  DEFAULT ('N') FOR [SMSSTOP]
GO

ALTER TABLE [contact].[PERSON] ADD  CONSTRAINT [BANNERSTOP_DEFAULT]  DEFAULT ('N') FOR [BANNERSTOP]
GO

ALTER TABLE [contact].[PERSON] ADD  CONSTRAINT [DF_IS_VULNERABLE]  DEFAULT ('N') FOR [IS_VULNERABLE]
GO

ALTER TABLE [contact].[PERSON]  WITH NOCHECK ADD  CONSTRAINT [FK_PER_IDVERINDRE] FOREIGN KEY([ID_VERIFIED_INDICATOR])
REFERENCES [reference].[ID_VERIFIED_INDICATOR_REF] ([ID_VERIFIED_INDICATOR])
GO

ALTER TABLE [contact].[PERSON] CHECK CONSTRAINT [FK_PER_IDVERINDRE]
GO

ALTER TABLE [contact].[PERSON]  WITH CHECK ADD  CONSTRAINT [FK_PERSON_SOURCE_FUNDS] FOREIGN KEY([SOURCE_FUNDS_ID])
REFERENCES [reference].[SOURCE_WEALTH_FUNDS_REF] ([SOURCE_WEALTH_FUNDS_ID])
GO

ALTER TABLE [contact].[PERSON] CHECK CONSTRAINT [FK_PERSON_SOURCE_FUNDS]
GO

ALTER TABLE [contact].[PERSON]  WITH CHECK ADD  CONSTRAINT [FK_PERSON_SOURCE_WEALTH] FOREIGN KEY([SOURCE_WEALTH_ID])
REFERENCES [reference].[SOURCE_WEALTH_FUNDS_REF] ([SOURCE_WEALTH_FUNDS_ID])
GO

ALTER TABLE [contact].[PERSON] CHECK CONSTRAINT [FK_PERSON_SOURCE_WEALTH]
GO

ALTER TABLE [contact].[PERSON]  WITH NOCHECK ADD  CONSTRAINT [PER_PER_SINGLECIF_FK] FOREIGN KEY([SINGLE_CIF])
REFERENCES [contact].[PERSON] ([PERSONID])
GO

ALTER TABLE [contact].[PERSON] CHECK CONSTRAINT [PER_PER_SINGLECIF_FK]
GO

ALTER TABLE [contact].[PERSON]  WITH CHECK ADD  CONSTRAINT [PERSON_EMPLOYMENT_TYPE_REF_FK] FOREIGN KEY([EMPLOYMENT_TYPE_REF_ID])
REFERENCES [reference].[EMPLOYMENT_TYPE_REF] ([EMPLOYMENT_TYPE_REF_ID])
GO

ALTER TABLE [contact].[PERSON] CHECK CONSTRAINT [PERSON_EMPLOYMENT_TYPE_REF_FK]
GO

